### ISSUE TITLE
It seems opts.small is not defined 

### ISSUE THREAD

**Issue by ja8143912** [Newbeeer/pfgmpp#2]
It seems that opts.small in train.py Line124/Line129 is not defined and assigned a value. It will give the following error:

  File "pfgmpp/train.py", line 124, in main
    if opts.small:
  File "pfgmpp/dnnlib/util.py", line 46, in __getattr__
    raise AttributeError(name)
AttributeError: small
python-BaseException

**Comment by Newbeeer** [comment]
Hi,

Thank you very much for pointing out the bug! I have fixed the bug. Sorry I pushed the code in a hurry.

Best,
Yilun
