### ISSUE TITLE
opts.pfgm is not defined

### ISSUE THREAD

**Issue by ja8143912** [Newbeeer/pfgmpp#3]
It seems opts.pfgm in train.py Line 162 c.update(rbatch=opts.rbatch, stf=opts.stf, pfgm=**opts.pfgm**, D=opts.aug_dim, pfgmpp=opts.pfgmpp) is not defined.

**Comment by Newbeeer** [comment]
Hi,

Thank you very much for pointing out the bug! I have fixed the bug. Sorry I pushed the code in a hurry.

Best,
Yilun
